name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64

    - name: Build and run the project
      run: make

    - name: Upload image.ppm as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: output-image
        path: image.ppm
